In [3]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

In [5]:
x2 = torch.load('x-file')
print(x2)

tensor([0, 1, 2, 3])


In [7]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [8]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [12]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 20)
        
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))
    
net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [13]:
torch.save(net.state_dict(), 'mlp_params')

In [14]:
clone = MLP()
clone.load_state_dict(torch.load('mlp_params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=20, bias=True)
)

In [15]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True]])

In [17]:
torch.device('cpu')

device(type='cpu')

In [18]:
torch.device('cuda')

device(type='cuda')

In [19]:
torch.device('cuda:1')

device(type='cuda', index=1)

In [20]:
torch.cuda.device_count()

1

In [21]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')